#!/usr/bin/env bash
set -euo pipefail

# Review this file before running it.
# Generated by PurgePilot; it does not execute automatically.

# Root: /workspaces/PurgePilot/testdata
# ondemand
# confidence=1.00 reason=Always delete as per config
rm -rf -- /workspaces/PurgePilot/testdata/ondemand

# __pycache__/module.pyc
# confidence=1.00 reason=Always delete as per config
rm -f -- /workspaces/PurgePilot/testdata/__pycache__/module.pyc

# __pycache__
# confidence=1.00 reason=Always delete as per config
rm -rf -- /workspaces/PurgePilot/testdata/__pycache__

# archive/archived.tar.gz
# confidence=0.80 reason=Downloaded archives are often no longer needed after extraction.
mkdir -p -- '/n/scratch/users/${USER:0:1}/$USER/PurgePilotRecycleBin/archive'
mv -n -- /workspaces/PurgePilot/testdata/archive/archived.tar.gz '/n/scratch/users/${USER:0:1}/$USER/PurgePilotRecycleBin/archive/archived.tar.gz'

# Downloads/downloaded.zip
# confidence=0.80 reason=Downloaded archives are often no longer needed after extraction.
mkdir -p -- '/n/scratch/users/${USER:0:1}/$USER/PurgePilotRecycleBin/Downloads'
mv -n -- /workspaces/PurgePilot/testdata/Downloads/downloaded.zip '/n/scratch/users/${USER:0:1}/$USER/PurgePilotRecycleBin/Downloads/downloaded.zip'
