#!/usr/bin/env bash
set -euo pipefail

# Review this file before running it.
# Generated by PurgePilot; it does not execute automatically.

# Root: /tmp/purgepilot-testdata
# ondemand
# confidence=1.00 reason=Always delete as per config
rm -rf -- /tmp/purgepilot-testdata/ondemand

# __pycache__/module.pyc
# confidence=1.00 reason=Always delete as per config
rm -f -- /tmp/purgepilot-testdata/__pycache__/module.pyc

# __pycache__
# confidence=1.00 reason=Always delete as per config
rm -rf -- /tmp/purgepilot-testdata/__pycache__

# archive/archived.tar.gz
# confidence=0.80 reason=Downloaded archive files can be removed if they are not actively used.
mkdir -p -- '/n/scratch/users/${USER:0:1}/$USER/PurgePilotRecycleBin/archive'
mv -n -- /tmp/purgepilot-testdata/archive/archived.tar.gz '/n/scratch/users/${USER:0:1}/$USER/PurgePilotRecycleBin/archive/archived.tar.gz'

# Downloads/downloaded.zip
# confidence=0.80 reason=Downloaded archive files can be removed if they are not actively used.
mkdir -p -- '/n/scratch/users/${USER:0:1}/$USER/PurgePilotRecycleBin/Downloads'
mv -n -- /tmp/purgepilot-testdata/Downloads/downloaded.zip '/n/scratch/users/${USER:0:1}/$USER/PurgePilotRecycleBin/Downloads/downloaded.zip'
